#
#    This is a snapcraft build script.
#    Copyright (C) 2022-2023 Jintao Yang <yjt950840@outlook.com>
#
#    This program is free software; you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation; either version 2 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License Version 2
#    along with this program; if not, write to the Free Software
#    Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
#
#    snapcraft.yaml:
#       snapcraft script.
#       build snap package on Linux.
#

# After registering a name on build.snapcraft.io, commit an uncommented line:
name: extreme-tux-racer
version: '0.8.3' # just for humans, typically '1.2+git' or '1.3.2'
summary: High speed arctic racing game based on Tux Racer. # 79 char long summary
description: |
  High speed arctic racing game based on Tux Racer.

  **For saving user data of scores, players, etc. Please install with 'devmode'.**

  `sudo snap install --devmode extreme-tux-racer`

  _more build details: https://github.com/Joker2770/etr-snap_

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core20
architectures:
  - build-on: amd64
  - build-on: armhf
  - build-on: arm64

plugs: # plugs for theming, font settings, cursor and to use gtk3 file chooser
  gtk-3-themes:
    interface: content
    target: $SNAP/data-dir/themes
    default-provider: gtk-common-themes
  icon-themes:
    interface: content
    target: $SNAP/data-dir/icons
    default-provider: gtk-common-themes
  sound-themes:
    interface: content
    target: $SNAP/data-dir/sounds
    default-provider: gtk-common-themes

plugs:
  dot-etr:
    interface: personal-files
    read:
      - $HOME/.etr/
plugs:
  dot-etr-options:
    interface: personal-files
    read:
      - $HOME/.etr/options.txt
plugs:
  dot-etr-highscore:
    interface: personal-files
    read:
      - $HOME/.etr/highscore
plugs:
  dot-etr-players:
    interface: personal-files
    read:
      - $HOME/.etr/players
plugs:
  etc-openal-alsoft:
    interface: system-files
    read:
      - /etc/openal/alsoft.conf

apps:
  extreme-tux-racer:
    command-chain: ["snap/command-chain/alsa-launch"]
    command: usr/local/bin/etr
    environment:
      LD_LIBRARY_PATH: ${SNAP}/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/pulseaudio
    extensions: [gnome-3-38]
    plugs:
      - home
      - audio-playback
      - pulseaudio
      - alsa
      - desktop
      - desktop-legacy
      - wayland
      - unity7
      - x11
      - opengl
      - gsettings
      - removable-media
      - etc-openal-alsoft
      - dot-etr
      - dot-etr-options
      - dot-etr-highscore
      - dot-etr-players

layout:
  /usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib:
    bind: $SNAP/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/alsa-lib
  /usr/local/share/etr:
    bind: $SNAP/usr/local/share/etr
  /usr/local/share/metainfo:
    bind: $SNAP/usr/local/share/metainfo
  /usr/local/share/pixmaps:
    bind: $SNAP/usr/local/share/pixmaps
  /usr/share/alsa:
    bind: $SNAP/usr/share/alsa
  /etc/fonts:
    bind: $SNAP/etc/fonts
    
parts:
  alsa-mixin:
    plugin: dump
    source: https://github.com/diddlesnaps/snapcraft-alsa.git
    source-subdir: snapcraft-assets
    build-packages:
      - libasound2-dev
    stage-packages:
      - libasound2
      - libasound2-plugins
      - yad
  extreme-tux-racer:
    after: [alsa-mixin]
    plugin: autotools
    source: "https://svn.code.sf.net/p/extremetuxracer/code/trunk"
    source-type: svn
    build-packages:
      - gcc
      - build-essential
      - automake
      - make
      - libsfml-dev
      - libsfml-system2.5
      - libglu1-mesa-dev
    autotools-configure-parameters:
      - --prefix=/usr/local
    stage-packages:
      - libsfml-window2.5
      - libsfml-system2.5
      - libsfml-network2.5
      - libsfml-graphics2.5
      - libsfml-audio2.5
      - libglu1-mesa
      - libpulse0
